---
# Это, вероятно, лучше, если вы не измените значение по умолчанию.
shardCount: 1

# Префикс по умолчанию Бастион. Это является постоянным, то есть однажды установленным, это останется
# то же самое, пока база данных не будет удалена.
# Хотя вы можете использовать команду `setPrefix` для изменения префикса сервера.
prefix:
  - "n!"

# Статус Бастиона по умолчанию.
# Допустимые значения: `online`,` idle`, `dnd` и` invisible` /
status: online

# Активность по умолчанию Бастион.
game:
 # Тип деятельности.
   # Допустимые значения: `Playing`,` Listening`, `Watching` и` Streaming`.
   # Обратите внимание, что действие Streaming будет работать только в действительном URL канала Twitch
   # добавляется в поле `url` ниже.
  type: Streaming
# Названия активности.
   # Строки, которые вы добавляете сюда, будут случайным образом вращаться в указанном интервале
   # в поле `interval` ниже.
  name:
    - "ту-ту-ру"
    - "смотри жиронимо тиви"
    - "бот ещё не готов"
    - "да до сих пор не готов"
    - "MaxWell ! бля"
    - "где-то был VL... а нет показалось"
    - "Д - Дискрименант"
    - "А - Армия"
    - "Р - Россия"
    - "Дальше будет то что будет..."
  # Переключить URL канала для потоковой передачи.
  url: https://www.twitch.tv/geronimovl
# Интервал вращения имени деятельности (в минутах).
  interval: 1

# Music настройки
music:
  # Если Bastion покажет название песни, которую он играет в данный момент,
   # деятельность?
  status: true
 # Сколько проходов должен пройти диспетчер Bastion при отправке пакетов
   # уменьшить потери пакетов для музыки. Значения свыше 5 не рекомендуются, так как это означает
   # вы используете в 5 раз больше пропускной способности.
  passes: 1

# Уровень логирования для бастиона. Меньшее значение означает меньше беспорядка в консоли 
#, а более высокое значение означает больше деталей в консоли. 
# Допустимые значения варьируются от 1 до 6
logLevel: 6
